### ISSUE TITLE
读取fii show.py文件报错

### ISSUE THREAD

**Issue by 18ghwg** [Kevin0412/pyfii#1]
pyfii1.1.0
**读取fii文件报错**

```
Traceback (most recent call last):
  File "C:\Users\观后无感\Desktop\fii文件读取demo\main.py", line 21, in <module>
    pf.show(data, t0, music, FPS=25, show=True)
  File "C:\Users\观后无感\Desktop\fii文件读取demo\pyfii\show.py", line 190, in show
    pygame.mixer.music.load(music_name)
UnboundLocalError: local variable 'music_name' referenced before assignment
```
以上是报错内容
我的代码：
```
import pyfii as pf

"""
pyfii 1.1.0 1.1.1都支持
"""
name = 'bai'  # fii配置文件所在的文件夹名称，文件夹放在程序同一目录下
data, t0, music = pf.read_fii(name)  # 读取fii配置文件数据
music = music if len(music) > 1 else []  # 针对没有音乐的文件让music变量为空列表

"""3D视角(评委视角)"""
# pf.show(data, t0, music, ThreeD=True, imshow=[90, 6], d=(600, 450), FPS=50, show=True)  # save="example"不保存视频
"""俯视视角"""
pf.show(data, t0, music, FPS=25, show=True)
"""无人机视角全景"""
pf.show(data, t0, music, ThreeD=True, FPS=20, track=[0], show=True)
"""定点全景"""
pf.show(data, t0, music, ThreeD=True, FPS=20, track=(280, 280, 165))
```

**Comment by Kevin0412** [comment]
感谢您的反馈。等到下周高考结束，我会对这个bug进行修改。此外，我还感谢您为我提出了解决方案。
高考临近，复习备考，无暇关照，请您谅解。
目前如果遇到上述bug按照上述方法解决即可。
